package main

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// patch 语义（v2，YAML 库实现）：
//   - runtime.yaml 是我们的生成物：键值对不变即可，顺序/注释/格式不保证
//   - 强制: tun.enable=true、dns.enable=true、external-ui=模块内置面板
//   - 保留用户的 external-controller / secret / 其余一切键值
//   - 绝不读写修改用户文件 config.yaml（只读）
//
// 同步生成 panel-config.js（悬浮面板用：API 地址 + secret）。

// defaultTun / defaultDNS 与模块默认模板一致。
var defaultTun = map[string]any{
	"enable":                true,
	"stack":                 "mixed",
	"auto-route":            true,
	"auto-detect-interface": true,
	"strict-route":          false,
	"dns-hijack":            []string{"0.0.0.0:53"},
}

var defaultDNS = map[string]any{
	"enable":             true,
	"enhanced-mode":      "fake-ip",
	"fake-ip-range":      "198.18.0.1/16",
	"fake-ip-filter":     []string{"*", "+.lan", "+.local"},
	"nameserver":         []string{"system", "udp://223.5.5.5"},
	"default-nameserver": []string{"223.5.5.5"},
}

func loadYAML(path string) (map[string]any, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	// 容忍 CRLF：统一去除 \r 再交给解析器
	b = []byte(strings.ReplaceAll(string(b), "\r", ""))
	var m map[string]any
	if err := yaml.Unmarshal(b, &m); err != nil {
		return nil, fmt.Errorf("配置解析失败: %w", err)
	}
	if m == nil {
		m = map[string]any{}
	}
	return m, nil
}

// writeRuntime 生成 runtime.yaml，返回是否成功。
func writeRuntime(cfg map[string]any) error {
	// ---- 强制 tun/dns enable ----
	for _, sect := range []string{"tun", "dns"} {
		v, ok := cfg[sect]
		if !ok || v == nil {
			continue // 缺段则注入默认块（下方）
		}
		sub, ok := v.(map[string]any)
		if !ok {
			// 类型异常(标量)，直接覆盖为默认块，保证 TUN 可用
			cfg[sect] = withEnable(defaultBlock(sect), true)
			continue
		}
		sub["enable"] = true
	}

	// ---- 强制 external-ui ----
	cfg["external-ui"] = dataUIDir

	out, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("runtime 序列化失败: %w", err)
	}
	header := "# === GENERATED by suclash_helper (runtime copy). 源文件: config.yaml (勿手改本文件) ===\n"
	tmp := runtimeCfg + ".tmp"
	if err := os.WriteFile(tmp, append([]byte(header), out...), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, runtimeCfg)
}

func defaultBlock(sect string) map[string]any {
	if sect == "tun" {
		return cloneMap(defaultTun)
	}
	return cloneMap(defaultDNS)
}

func withEnable(m map[string]any, en bool) map[string]any {
	m["enable"] = en
	return m
}

func cloneMap(src map[string]any) map[string]any {
	dst := make(map[string]any, len(src))
	for k, v := range src {
		dst[k] = v
	}
	return dst
}

// writePanelConfig 生成 DATA_UI_DIR/panel-config.js。
func writePanelConfig(cfg map[string]any) error {
	host, port := "127.0.0.1", "9090"
	if ec, ok := cfg["external-controller"].(string); ok && ec != "" {
		h, p, ok2 := splitHostPort(ec)
		if ok2 {
			host, port = h, p
		}
	}
	secret, _ := cfg["secret"].(string)

	var b strings.Builder
	b.WriteString("window.__SUCLASH__={api:{protocol:\"http\",host:\"")
	b.WriteString(escapeJS(host))
	b.WriteString("\",port:\"")
	b.WriteString(escapeJS(port))
	b.WriteString("\",secret:\"")
	b.WriteString(escapeJS(secret))
	b.WriteString("\"}};\n")
	return os.WriteFile(dataUIDir+"/panel-config.js", []byte(b.String()), 0o644)
}

// splitHostPort 解析 external-controller 值（支持 IPv4/域名/IPv6[...]）。
func splitHostPort(s string) (string, string, bool) {
	s = strings.TrimSpace(s)
	if s == "" {
		return "", "", false
	}
	if strings.HasPrefix(s, "[") { // [::1]:9090
		i := strings.Index(s, "]")
		if i < 0 {
			return "", "", false
		}
		host := s[1:i]
		rest := s[i+1:]
		if strings.HasPrefix(rest, ":") {
			return normHost(host), rest[1:], true
		}
		return normHost(host), "9090", true
	}
	i := strings.LastIndex(s, ":")
	if i < 0 {
		return normHost(s), "9090", true
	}
	return normHost(s[:i]), s[i+1:], true
}

func normHost(h string) string {
	switch h {
	case "0.0.0.0", "*", "::", "":
		return "127.0.0.1"
	}
	return h
}

func escapeJS(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "'", `\'`, "\n", `\n`, "\r", "")
	return r.Replace(s)
}

// ensureDefaultConfig 首次安装无用户配置时放置默认模板。
func ensureDefaultConfig() (bool, error) {
	if _, err := os.Stat(userCfg); err == nil {
		return false, nil
	}
	b, err := os.ReadFile(defaultCfg)
	if err != nil {
		return false, err
	}
	if err := os.WriteFile(userCfg, b, 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// doPatch: 读取用户配置 → 强制字段 → runtime.yaml + panel-config.js
func doPatch() error {
	_, err := ensureDefaultConfig()
	if err != nil {
		return fmt.Errorf("默认配置放置失败: %w", err)
	}
	cfg, err := loadYAML(userCfg)
	if err != nil {
		return err
	}
	// 缺 tun / dns 段时注入默认块
	if _, ok := cfg["tun"]; !ok {
		cfg["tun"] = withEnable(defaultBlock("tun"), true)
	}
	if _, ok := cfg["dns"]; !ok {
		cfg["dns"] = withEnable(defaultBlock("dns"), true)
	}
	if _, ok := cfg["external-controller"]; !ok {
		cfg["external-controller"] = apiAddr
	}
	if err := writeRuntime(cfg); err != nil {
		return err
	}
	return writePanelConfig(cfg)
}

func cmdPatch(args []string) error {
	if err := doPatch(); err != nil {
		return err
	}
	fmt.Println("patched")
	return nil
}
