#!/system/bin/sh
# patch_config.sh - 由用户配置生成运行时配置 runtime.yaml（绝不修改用户文件）
# 仅在"缺失导致 TUN 模式无法工作/WebUI 不可用"时补充最小字段：
#   tun.enable / dns.enable / external-controller / external-ui
# 其余内容逐字节保留用户配置。

. /data/adb/modules/ksuclash/scripts/common.sh

[ -f "$USER_CFG" ] || { echo "no user config: $USER_CFG"; exit 1; }
[ -x "$BIN_DIR/mihomo" ] || { echo "mihomo binary missing"; exit 1; }

TMP="$RUNTIME_CFG.tmp"

# 注意：经 tr 去除 \r（用户配置可能是 CRLF），并显式传入用户配置文件
"$BB" tr -d '\r' < "$USER_CFG" | "$BB" awk -v modui="$DATA_UI_DIR" -v tmp="$TMP" '
function rmtail(s) { sub(/[ \t]*#.*$/, "", s); sub(/[ \t]+$/, "", s); return s }
BEGIN {
    patch_n = 0
}
{
    raw[NR] = $0
    line = $0

    # 顶层键
    if (line ~ /^[A-Za-z][A-Za-z0-9_-]*[ \t]*:/) {
        key = line; sub(/[ \t]*:.*/, "", key)
        if (key == "tun" || key == "dns") { sect = key; seen[key] = 1 }
        else { sect = "" }
        if (key == "external-controller") seen_ec = 1
        if (key == "external-ui") seen_eui = 1
        if (key == "secret") seen_secret = 1
    }

    if (sect != "") {
        if (line ~ /^[ \t]+enable[ \t]*:/) {
            v = rmtail(line); sub(/^[ \t]+enable[ \t]*:[ \t]*/, "", v)
            if (sect == "tun") tun_en = v
            else dns_en = v
        }
    }
}
END {
    # ---- 计算 tun 补丁 ----
    tun_flip = 0; tun_insert = 0
    if (seen["tun"]) {
        if (tun_en == "false") tun_flip = 1
        else if (tun_en == "") tun_insert = 1
    }

    # ---- 计算 dns 补丁 ----
    dns_flip = 0; dns_insert = 0
    if (seen["dns"]) {
        if (dns_en == "false") dns_flip = 1
        else if (dns_en == "") dns_insert = 1
    }

    # ---- 输出头 ----
    print "# === GENERATED by KSU Clash (runtime copy). 源文件: /data/adb/ksuclash/config.yaml (勿手改本文件) ==="
    print "# applied patches:"
    if (tun_flip)    print "#   - tun.enable: false -> true"
    if (tun_insert)  print "#   - tun 段缺少 enable, 已插入 enable: true"
    if (!seen["tun"]) print "#   - 缺少 tun 段, 已追加(TUN+auto-route+mixed)"
    if (dns_flip)    print "#   - dns.enable: false -> true"
    if (dns_insert)  print "#   - dns 段缺少 enable, 已插入 enable: true"
    if (!seen["dns"]) print "#   - 缺少 dns 段, 已追加(fake-ip + hijack 兜底)"
    if (!seen_ec)    print "#   - 缺少 external-controller, 已追加 127.0.0.1:9090"
    if (!seen_eui)   print "#   - 缺少 external-ui, 已指向模块内置 zashboard"
    print ""

    # ---- 输出原配置（带补丁）----
    n = NR
    for (i = 1; i <= n; i++) {
        line = raw[i]
        key = ""
        if (line ~ /^[A-Za-z][A-Za-z0-9_-]*[ \t]*:/) {
            key = line; sub(/[ \t]*:.*/, "", key)
        }
        if (key == "tun" && tun_flip) {
            print line; sect_tun = 1; continue
        }
        if (key == "dns" && dns_flip) {
            print line; sect_dns = 1; continue
        }
        if (sect_tun && line ~ /^[ \t]+enable[ \t]*:[ \t]*false[ \t]*(#.*)?$/) {
            sub(/false/, "true", line); sect_tun = 0; print line; continue
        }
        if (sect_dns && line ~ /^[ \t]+enable[ \t]*:[ \t]*false[ \t]*(#.*)?$/) {
            sub(/false/, "true", line); sect_dns = 0; print line; continue
        }
        if (key == "tun" && tun_insert) {
            print line
            # 继承原缩进风格
            ind = line; sub(/[^ \t].*$/, "", ind); if (ind == "") ind = "  "
            print ind "enable: true"
            continue
        }
        if (key == "dns" && dns_insert) {
            print line
            ind = line; sub(/[^ \t].*$/, "", ind); if (ind == "") ind = "  "
            print ind "enable: true"
            continue
        }
        print line
    }

    # ---- 追加缺失块 ----
    if (!seen["tun"]) {
        print ""
        print "# --- appended by ksuclash: TUN 模式（原配置缺失该段）---"
        print "tun:"
        print "  enable: true"
        print "  stack: mixed"
        print "  auto-route: true"
        print "  auto-detect-interface: true"
        print "  strict-route: false"
        print "  dns-hijack:"
        print "    - 0.0.0.0:53"
    }
    if (!seen["dns"]) {
        print ""
        print "# --- appended by ksuclash: 内置 DNS（原配置缺失该段）---"
        print "dns:"
        print "  enable: true"
        print "  enhanced-mode: fake-ip"
        print "  fake-ip-range: 198.18.0.1/16"
        print "  fake-ip-filter:"
        print "    - \"*\""
        print "    - \"+.lan\""
        print "    - \"+.local\""
        print "  nameserver:"
        print "    - system"
        print "    - udp://223.5.5.5"
        print "  default-nameserver:"
        print "    - 223.5.5.5"
    }
    if (!seen_ec) {
        print ""
        print "# --- appended by ksuclash: 本机外部控制器 ---"
        print "external-controller: 127.0.0.1:9090"
    }
    if (!seen_eui) {
        print ""
        print "# --- appended by ksuclash: 模块内置 zashboard ---"
        print "external-ui: " modui
    }
}
' > "$TMP" 2> /data/adb/ksuclash/.patcherr

_rc=$?
if [ $_rc -ne 0 ] || [ ! -s "$TMP" ]; then
    echo "patch failed: $(cat /data/adb/ksuclash/.patcherr 2>/dev/null)"
    rm -f "$TMP"
    exit 1
fi

mv -f "$TMP" "$RUNTIME_CFG"
rm -f /data/adb/ksuclash/.patcherr

# 同步生成 WebUI 面板配置（zashboard 悬浮面板用：API 地址 + secret）
"$BB" awk '
    { line=$0; sub(/[ \t]*#.*$/, "", line) }
    /^external-controller:/ { v=line; sub(/^external-controller:[ \t]*/, "", v); ec=v }
    /^secret:/              { v=line; sub(/^secret:[ \t]*/, "", v);
                              gsub(/^["'\'']/, "", v); gsub(/["'\'']$/, "", v); sec=v }
    END {
        host="127.0.0.1"; port="9090"
        n = split(ec, a, ":")
        if (n >= 2) {
            port = a[n]
            if (ec !~ /^\[/) { host = ec; sub(/:[^:]*$/, "", host) }
            if (host == "0.0.0.0" || host == "*" || host == "::") host = "127.0.0.1"
        }
        gsub(/\\/, "\\\\", sec); gsub(/"/, "\\\"", sec)
        printf "window.__KSUCLASH__={api:{protocol:\"http\",host:\"%s\",port:\"%s\",secret:\"%s\"}};\n", host, port, sec
    }
' "$RUNTIME_CFG" > "$DATA_UI_DIR/panel-config.js" 2>/dev/null || true

exit 0
